// Generated by CoffeeScript 1.4.0
var server;

server = function(options) {
  var app, asset_js_path, assets, express, file, resource, stripExt, stylus, _;
  express = require('express');
  stylus = require('stylus');
  assets = require('connect-assets');
  resource = require('express-resource');
  file = require("file");
  _ = require("underscore");
  app = express();
  app.use(assets());
  stripExt = function(filePath) {
    var lastDotIndex;
    if ((lastDotIndex = filePath.lastIndexOf('.')) >= 0) {
      return filePath.slice(0, lastDotIndex);
    } else {
      return filePath;
    }
  };
  asset_js_path = "" + (process.cwd()) + "/assets/js/";
  file.walkSync(asset_js_path, function(dirPath, dirs, files) {
    if (files != null) {
      files.map(_.compose(assets.instance.options.helperContext.js, stripExt));
    }
    return true;
  });
  app.use(express["static"](process.cwd() + '/public'));
  app.use(express.bodyParser());
  app.set('view engine', 'jade');
  app.get('/', function(req, resp) {
    return resp.render('index');
  });
  app.get('/data', function(req, resp) {
    var json;
    json = require('../data/techradar.json');
    resp.set({
      'Content-Type': 'text/json'
    });
    return resp.send(json);
  });
  app.resource('punters', require('./punter').resource(options));
  return app;
};

exports.server = server;
