// Generated by CoffeeScript 1.4.0
var db, db_url, mongoose, port, with_db;

mongoose = require('mongoose');

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

db_url = process.env.MONGOLAB_URL || "mongodb://localhost//yow_game";

with_db = function(db) {
  var options;
  options = {
    db: db
  };
  console.log(options);
  return require('./app').server(options).listen(port, function() {
    return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
  });
};

db = mongoose.connect(db_url);

db.connections[0].once('open', function() {
  return with_db(db);
});

db.connections[0].on('error', function() {
  return with_db(null);
});
