// Generated by CoffeeScript 1.4.0
var app, assets, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return resp.render('index');
});

app.get('/data', function(req, resp) {
  var json;
  json = require('../data/techradar.json');
  resp.set({
    'Content-Type': 'text/json'
  });
  return resp.send(json);
});

var mongoose = require('mongoose'),
	  db_url = process.env.MONGOLAB_URL || "mongodb://localhost//yow_game",
	  db = mongoose.connect(db_url)
	  Schema = mongoose.Schema;

var PunterSchema = new Schema({
	fullName: String,
	company: String,
	emailAddress: String
});
var PunterModel = db.model("punters", PunterSchema);

app.get('/punters/:id', function(req, resp){
	return PunterModel.find({_id: req.param('id')}, function(err, punter){
		return resp.send(200, punter);
	})
});

app.post('/punters', function(req, resp){
	var punter = new PunterModel();
	punter.fullName = "Mr Unknowable";
	punter.company = "ThoughtWorks";
	punter.emailAddress = "someone@somewhere";
	punter.save();

	return resp.redirect('punters/' + punter._id);
});

app.get('/result', function(req, resp) {
  return resp.render('result');
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
