// Generated by CoffeeScript 1.4.0
var db_url, mongoose, options, port;

mongoose = require('mongoose');

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

db_url = process.env.MONGOLAB_URL || "mongodb://localhost//yow_game";

options = {};

require('./app').server(options).listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
